import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import 'zone.js';  

// 💡 Correct import for modern Amplify libraries
import { Amplify } from 'aws-amplify';
// 💡 The new configuration file generated by Amplify Gen 2
import outputs from '../amplify_outputs.json';
import { provideHttpClient } from '@angular/common/http';
import { parseAmplifyConfig } from 'aws-amplify/utils';

const amplifyConfig = parseAmplifyConfig(outputs);

Amplify.configure(
  {
    ...amplifyConfig,
    API: {
      ...amplifyConfig.API,
      REST: outputs.custom.API,
    },
  },
  {
    API: {
      REST: {
        retryStrategy: {
          strategy: 'no-retry', // Overrides default retry strategy
        },
      }
    }
  }
);

bootstrapApplication(AppComponent, {
  providers: [
    provideHttpClient()
  ]
}).catch(err => console.error(err));

